import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Curso NextJS 13 - First Steps',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col w-full min-h-screen overflow-hidden text-white bg-slate-700'>
          <div className='flex-grow'>{children}</div>
        </div>
      </body>
    </html>
  );
}
